/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "INA226_I2C.h"
#include "INA226_I2C_I2C.h"
#include "INA226_I2C_PINS.h"
#include "INA226_I2C_I2C_PVT.h"
#include "INA226_I2C_PVT.h"
#include "INA226_I2C_BOOT.h"
#include "I2C_Brain.h"
#include "I2C_Brain_I2C.h"
#include "I2C_Brain_PINS.h"
#include "I2C_Brain_I2C_PVT.h"
#include "I2C_Brain_PVT.h"
#include "I2C_Brain_BOOT.h"
#include "Jetty.h"
#include "Jetty_I2C.h"
#include "Jetty_PINS.h"
#include "Jetty_I2C_PVT.h"
#include "Jetty_PVT.h"
#include "Jetty_BOOT.h"
#include "DBG_UART.h"
#include "DBG_UART_SPI_UART.h"
#include "DBG_UART_PINS.h"
#include "DBG_UART_SPI_UART_PVT.h"
#include "DBG_UART_PVT.h"
#include "DBG_UART_BOOT.h"
#include "INA226_I2C_SCBCLK.h"
#include "INA226_I2C_sda.h"
#include "INA226_I2C_sda_aliases.h"
#include "INA226_I2C_scl.h"
#include "INA226_I2C_scl_aliases.h"
#include "INA226_I2C_SCB_IRQ.h"
#include "I2C_Brain_SCBCLK.h"
#include "I2C_Brain_sda.h"
#include "I2C_Brain_sda_aliases.h"
#include "I2C_Brain_scl.h"
#include "I2C_Brain_scl_aliases.h"
#include "I2C_Brain_SCB_IRQ.h"
#include "Jetty_SCBCLK.h"
#include "Jetty_sda.h"
#include "Jetty_sda_aliases.h"
#include "Jetty_scl.h"
#include "Jetty_scl_aliases.h"
#include "Jetty_SCB_IRQ.h"
#include "DBG_UART_SCBCLK.h"
#include "DBG_UART_tx.h"
#include "DBG_UART_tx_aliases.h"
#include "DBG_UART_rx.h"
#include "DBG_UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

